# Generated by Django 4.2.7 on 2023-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
